// 首次初始化时写入的预设模板 —— 解决「空模板列表不知道从哪下手」的起步门槛
export const STARTER_TEMPLATES = [
  {
    name: '跑步',
    emoji: '🏃',
    color: '#5B9BF3',
    mode: 'checkin',
    group: '健康',
    description: '每次跑完点一下，累计成轨迹',
    goalValue: 20,
    goalPeriod: 'month',
    fields: [
      { key: 'distance', label: '距离', type: 'number', unit: 'km', placeholder: '0.0' },
      { key: 'duration', label: '用时', type: 'number', unit: '分钟', placeholder: '0' },
      { key: 'feeling', label: '体感', type: 'select', options: ['轻松', '正常', '吃力', '很累'] },
      { key: 'note', label: '备注', type: 'text', placeholder: '路线、天气、状态…' },
    ],
  },
  {
    name: '阅读',
    emoji: '📖',
    color: '#7F77DD',
    mode: 'checkin',
    group: '学习',
    description: '每天读了多少，一年后回头看',
    goalValue: 26,
    goalPeriod: 'month',
    fields: [
      { key: 'book', label: '书名', type: 'text', placeholder: '正在读的书' },
      { key: 'pages', label: '页数', type: 'number', unit: '页', placeholder: '0' },
      { key: 'minutes', label: '时长', type: 'number', unit: '分钟', placeholder: '0' },
      { key: 'highlight', label: '摘录', type: 'text', placeholder: '今天记下的一句话' },
    ],
  },
  {
    name: '喝水',
    emoji: '💧',
    color: '#378ADD',
    mode: 'checkin',
    group: '健康',
    description: '一天多次，随手补一下',
    goalValue: 8,
    goalPeriod: 'day',
    fields: [{ key: 'amount', label: '水量', type: 'number', unit: 'ml', placeholder: '250' }],
  },
  {
    name: '冥想',
    emoji: '🧘',
    color: '#1D9E75',
    mode: 'checkin',
    group: '健康',
    description: '静坐计时，结束后自动留痕',
    goalValue: 15,
    goalPeriod: 'month',
    fields: [
      { key: 'minutes', label: '时长', type: 'number', unit: '分钟' },
      { key: 'quality', label: '专注度', type: 'select', options: ['很好', '一般', '走神较多'] },
    ],
  },
  {
    name: '心情',
    emoji: '🫧',
    color: '#D4537E',
    mode: 'record',
    group: '生活',
    description: '给每一天的情绪留个坐标',
    goalValue: 0,
    goalPeriod: 'month',
    fields: [
      { key: 'mood', label: '情绪', type: 'select', options: ['很好', '还行', '一般', '低落'] },
      { key: 'energy', label: '精力', type: 'rating', max: 5 },
      { key: 'text', label: '想说的话', type: 'text', placeholder: '发生了什么' },
    ],
  },
  {
    name: '随手记',
    emoji: '📌',
    color: '#BA7517',
    mode: 'record',
    group: '生活',
    description: '灵感、待办、想法，先记下来再说',
    goalValue: 0,
    goalPeriod: 'month',
    fields: [
      { key: 'text', label: '内容', type: 'text', placeholder: '想到什么写什么' },
      { key: 'photo', label: '图片', type: 'image' },
      { key: 'kind', label: '类型', type: 'select', options: ['灵感', '待办', '收藏', '其他'] },
    ],
  },
];
